import { useEffect, useState } from "react";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { PlusCircle, Loader2, CheckCircle, Search } from "lucide-react";
import { api } from "@/lib/api";
import DashboardLayout from "@/components/DashboardLayout";
import { toast } from "sonner";

interface UserOption {
  id: string;
  email: string;
}

const DeviceRegister = () => {
  const [pairCode, setPairCode] = useState("");
  const [location, setLocation] = useState("");
  const [userEmailQuery, setUserEmailQuery] = useState("");
  const [userOptions, setUserOptions] = useState<UserOption[]>([]);
  const [selectedUser, setSelectedUser] = useState<UserOption | null>(null);
  const [searchingUsers, setSearchingUsers] = useState(false);
  const [hasSearched, setHasSearched] = useState(false);
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<{ device_id: string; status: string } | null>(null);

  const searchUsers = async (queryParam?: string, showShortQueryToast = true) => {
    const query = (queryParam ?? userEmailQuery).trim();
    if (query.length < 2) {
      setUserOptions([]);
      setHasSearched(false);
      if (showShortQueryToast) {
        toast.error("Enter at least 2 characters to search users");
      }
      return;
    }

    setSearchingUsers(true);
    setHasSearched(true);
    try {
      const rows = await api<UserOption[]>(`/admin/users/search?q=${encodeURIComponent(query)}`);
      setUserOptions(rows);
      if (rows.length === 0 && showShortQueryToast) {
        toast.error("No users found for this email");
      }
    } catch (err: unknown) {
      toast.error(err instanceof Error ? err.message : "User search failed");
    } finally {
      setSearchingUsers(false);
    }
  };

  useEffect(() => {
    const query = userEmailQuery.trim();
    if (query.length < 2) {
      setUserOptions([]);
      setHasSearched(false);
      return;
    }

    const timer = window.setTimeout(() => {
      void searchUsers(query, false);
    }, 350);

    return () => window.clearTimeout(timer);
  }, [userEmailQuery]);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!pairCode.trim() || !location.trim() || !selectedUser) {
      toast.error("Pair code, location, and user selection are required");
      return;
    }
    setLoading(true);
    setResult(null);
    try {
      const data = await api<{ device_id: string; status: string }>("/admin/device/register", {
        method: "POST",
        body: JSON.stringify({
          pair_code: pairCode.trim(),
          location: location.trim(),
          user_id: selectedUser.id,
        }),
      });
      setResult(data);
      toast.success("Device registered successfully!");
      setPairCode("");
      setLocation("");
      setUserEmailQuery("");
      setUserOptions([]);
      setHasSearched(false);
      setSelectedUser(null);
    } catch (err: unknown) {
      toast.error(err instanceof Error ? err.message : "Registration failed");
    } finally {
      setLoading(false);
    }
  };

  return (
    <DashboardLayout>
      <div className="max-w-lg mx-auto">
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <PlusCircle className="h-5 w-5" />
              Register New Device
            </CardTitle>
            <CardDescription>Pair a new smart meter device to a user</CardDescription>
          </CardHeader>
          <form onSubmit={handleSubmit}>
            <CardContent className="space-y-4">
              <div className="space-y-2">
                <Label htmlFor="pairCode">Pair Code</Label>
                <Input
                  id="pairCode"
                  placeholder="e.g. 482913"
                  value={pairCode}
                  onChange={(e) => setPairCode(e.target.value)}
                  required
                  maxLength={10}
                />
                <p className="text-xs text-muted-foreground">
                  Enter the 6-digit code generated by the meter via backend pairing flow.
                </p>
              </div>
              <div className="space-y-2">
                <Label htmlFor="location">Location</Label>
                <Input
                  id="location"
                  placeholder="e.g. Room 201"
                  value={location}
                  onChange={(e) => setLocation(e.target.value)}
                  required
                  maxLength={100}
                />
              </div>
              <div className="space-y-2">
                <Label htmlFor="userEmail">Find User by Email</Label>
                <div className="flex gap-2">
                  <Input
                    id="userEmail"
                    placeholder="Type user email"
                    value={userEmailQuery}
                    onChange={(e) => setUserEmailQuery(e.target.value)}
                  />
                  <Button type="button" variant="outline" onClick={searchUsers} disabled={searchingUsers}>
                    {searchingUsers ? <Loader2 className="h-4 w-4 animate-spin" /> : <Search className="h-4 w-4" />}
                  </Button>
                </div>

                {userOptions.length > 0 && (
                  <div className="rounded-md border divide-y max-h-40 overflow-auto">
                    {userOptions.map((user) => (
                      <button
                        key={user.id}
                        type="button"
                        className="w-full text-left px-3 py-2 hover:bg-muted text-sm"
                        onClick={() => setSelectedUser(user)}
                      >
                        {user.email}
                      </button>
                    ))}
                  </div>
                )}

                {hasSearched && !searchingUsers && userOptions.length === 0 && userEmailQuery.trim().length >= 2 && (
                  <p className="text-xs text-muted-foreground">No users found for this search.</p>
                )}

                {selectedUser && (
                  <div className="rounded-md border border-energy/30 bg-energy/10 px-3 py-2 text-sm">
                    Selected User: <span className="font-medium">{selectedUser.email}</span>
                  </div>
                )}
              </div>
            </CardContent>
            <CardFooter className="flex-col gap-3">
              <Button type="submit" className="w-full bg-electric hover:bg-electric/90" disabled={loading}>
                {loading && <Loader2 className="h-4 w-4 animate-spin" />}
                Register Device
              </Button>

              {result && (
                <div className="w-full rounded-lg border border-energy/30 bg-energy/10 p-4 flex items-start gap-3">
                  <CheckCircle className="h-5 w-5 text-energy mt-0.5" />
                  <div>
                    <p className="font-medium text-sm">Device Registered</p>
                    <p className="text-sm text-muted-foreground">
                      ID: <span className="font-mono">{result.device_id}</span> — Status: {result.status}
                    </p>
                  </div>
                </div>
              )}
            </CardFooter>
          </form>
        </Card>
      </div>
    </DashboardLayout>
  );
};

export default DeviceRegister;
